name: Deploy to server

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Ionic
        run: npm install -g @ionic/cli

      - name: Install dependencies
        run: npm install

      - name: Add env files prod
        run: echo "${{ secrets.ENVPROD }}" > src/environments/env.prod.exclude.ts

      - name: Build
        run: ionic build --prod

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: www
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          REMOTE_PORT: ${{ secrets.PORT }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          SCRIPT_AFTER: |
            sudo rm -rf ${{ secrets.DEPLOYMENT_TARGET }}
            sudo mv ${{ secrets.REMOTE_TARGET }}/www ${{ secrets.DEPLOYMENT_TARGET }}

